config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'googledrive#index'
  get '/googledrive/get_docs', to: 'googledrive#get_docs'
  get '/docs', to: 'googledrive#docs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/google_drive_datum.rb
class GoogleDriveDatum < ApplicationRecord
  MAX_DEPTH = 99
  MAX_DEPTH.freeze

  #0:通常
  #1:テスト用ロジック実行
  EXEC_MODE = 0
  EXEC_MODE.freeze

  def self.search_all
    client_id     = ENV["CLIENT_ID"]
    client_secret = ENV["CLIENT_SECRET"]
    refresh_token = ENV["REFRESH_TOKEN"]

    client = OAuth2::Client.new(
        client_id,
        client_secret,
        site: "https://accounts.google.com",
        token_url: "/o/oauth2/token",
        authorize_url: "/o/oauth2/auth"
    )
    auth_token = OAuth2::AccessToken.from_hash(client,{:refresh_token => refresh_token, :expires_at => 3600})
    auth_token = auth_token.refresh!
    @session = GoogleDrive.login_with_oauth(auth_token.token)

    #DBデータ更新
    GoogleDriveDatum.delete_all
    search("'root' in parents and trashed = false and 'me' in owners", 0, '', '/')
  end

  def self.search(q, depth, parent, filepath)
    @session.files(q: q) do |file|
      # get owners
      owners = []
      file.owners.each do |owner|
        owners << "#{owner.try(:display_name)} <#{owner.try(:email_address)}>"
      end

      permissions = []
      file.permissions.each do |permission|
        permissions << "#{permission.role}:#{permission.display_name} <#{permission.try(:type)}>"
      end

      #ドキュメントの中身取得
      content = ""
      if file.mime_type == 'application/vnd.google-apps.document'
        filedir = "public/output_file/" + file.id
        @session.drive.export_file(file.id,'text/html',download_dest: filedir)
        content = filedir
      end

      #各種情報取得
      id = file.id
      title = file.title
      mime_type = file.mime_type
      icon_link = file.icon_link
      web_view_link = file.web_view_link

      if EXEC_MODE == 1
        change_txt_to_docs(file, parent)
      end

      hash = {
        :fileid => id,
        :title => title,
        :depth => depth,
        :mime_type => mime_type,
        :icon_link => icon_link,
        :web_view_link => web_view_link,
        :parent => parent,
        :owner => owners,
        :permission => permissions,
        :filepath => filepath,
        :fullpath => filepath + title,
        :content => content
      }

      #Google Drive APIより取得したデータをテーブルに保存
      google_drive_data = GoogleDriveDatum.new
      google_drive_data.attributes = hash
      google_drive_data.save

      #フォルダーの中を検索
      if file.mime_type == 'application/vnd.google-apps.folder' and depth < MAX_DEPTH
        search("'#{file.id}' in parents and trashed = false and 'me' in owners", depth + 1, file.id, filepath + title + '/')
      end
    end
  end

  #.txtをGoogle Docsに変換
  def self.change_txt_to_docs(file, parent)
    if file.mime_type == 'text/plain'
      old_file_id = file.id

      #旧ファイル取得
      @session.drive.get_file(file.id, download_dest: "dummy.txt")
      #新ファイル作成
      file_metadata = {
          name: file.title.gsub(/.txt/, ""),
          parents: [parent],
          mime_type: 'application/vnd.google-apps.document'
      }
      @session.drive.create_file(file_metadata,
                                 fields: 'id',
                                 upload_source: 'dummy.txt',
                                 content_type: file.mime_type)
      #旧ファイル削除
      @session.drive.delete_file(old_file_id)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/googledrive_controller.rb
class GoogledriveController < ApplicationController
  protect_from_forgery except: :get_docs # get_docsアクションを除外

  def index
    @files = GoogleDriveDatum.order('fullpath')
  end

  def docs
    @files = GoogleDriveDatum.where("content <> ''").order('fullpath')
  end

  def get_docs
    ajax_action unless params[:ajax_handler].blank?

    # Ajaxリクエストではない時の処理
  end

  def ajax_action
    if params[:ajax_handler] == 'handle_name1'
      # Ajaxの処理
      id = params[:id]
      @data = GoogleDriveDatum.find(id)
      @output_html = "表示不可"
      if @data.content != ""
        File.open(@data.content, "r") do |f|
          @output_html = f.read
        end
      end
      render
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/googledrive_helper.rb
module GoogledriveHelper
end

app/views/googledrive/_ajax_container.html.erb
<h2><%= @data.title %></h2>
<p><%= @data.filepath %></p>
<hr>
<p><%= @output_html.html_safe %></p>

app/views/googledrive/docs.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 sidebar">
      <ul class="list-group">
      <% @files.each do |file| %>
        <li class="list-group-item">
          <img src="<%= file[:icon_link] %>" />
          <%= link_to file[:title], googledrive_get_docs_path(ajax_handler: 'handle_name1', id: file.id), remote: true %>
          <a href="<%= file[:web_view_link] %>" target="_blank">
            <span class="glyphicon glyphicon-new-window"></span>
          </a>
        </li>
      <% end %>
      </ul>
    </div>
    <div class="col-6 offset-6">
      <div id="ajax-response-wrapper" />
    </div>
  </div>
</div>

app/views/googledrive/get_docs.js.erb
$('#ajax-response-wrapper').html('<%=j render partial: "ajax_container" %>');

app/views/googledrive/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 sidebar">
      <ul class="list-group">
      <% @files.each do |file| %>
        <li class="list-group-item">
          <span style="padding-left:<%= file[:depth] * 20 %>px;"><img src="<%= file[:icon_link] %>" />
            <%= link_to file[:title], googledrive_get_docs_path(ajax_handler: 'handle_name1', id: file.id), remote: true %>
            <a href="<%= file[:web_view_link] %>" target="_blank">
              <span class="glyphicon glyphicon-new-window"></span>
            </a>
          </span>
        </li>
      <% end %>
      </ul>
    </div>
    <div class="col-6 offset-6">
      <div id="ajax-response-wrapper" />
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>